version: "3"

services:
  lid-nginx:
    restart: always
    image: nginx:stable-alpine
    container_name: lid-nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  lid-nginx-exporter:
    restart: always
    image: nginx/nginx-prometheus-exporter:0.9.0
    container_name: lid-nginx-exporter
    depends_on:
      - lid-nginx
    ports:
      - 9113:9113
    command: ["-nginx.scrape-uri=http://lid-nginx/nginx_status"]

  lid-prometheus:
    restart: always
    image: prom/prometheus:main
    container_name: lid-prometheus
    depends_on:
      - lid-nginx-exporter
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  lid-grafana:
    restart: always
    image: grafana/grafana:main
    container_name: lid-grafana
    depends_on:
      - lid-prometheus
    ports:
      - 3000:3000
